-- ============================================
-- CONSOLIDATED DATABASE SCHEMA
-- Negotiation Experiment Platform (Self-Hosted PostgreSQL)
-- ============================================
--
-- This file is a single consolidated migration for running on plain
-- PostgreSQL 16+ (no Supabase). It was generated by concatenating
-- migrations 001 through 023 in order, with the following removals:
--
--   - ALTER PUBLICATION supabase_realtime ...  (Supabase-only)
--   - ALTER TABLE ... ENABLE ROW LEVEL SECURITY (Supabase-only)
--   - CREATE POLICY / DROP POLICY ...          (Supabase-only)
--
-- Functions that were replaced by later migrations still appear in
-- order; the OR REPLACE clause makes this safe.
--
-- Run on a fresh database:
--   psql -U postgres -d your_db -f init.sql
-- ============================================


-- ============================================================
-- Migration 001: Initial Schema
-- ============================================================

-- Enable UUID extension (works on plain PostgreSQL)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================
-- 1. PARTICIPANTS TABLE
-- Stores participant information and questionnaire data
-- ============================================
CREATE TABLE participants (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    demographic_data JSONB DEFAULT '{}'::jsonb,
    pre_questionnaire_data JSONB DEFAULT '{}'::jsonb,
    post_questionnaire_data JSONB DEFAULT '{}'::jsonb
);

COMMENT ON TABLE participants IS 'Stores participant information and survey responses';
COMMENT ON COLUMN participants.demographic_data IS 'Demographics collected during pre-survey (age, gender, education, etc.)';
COMMENT ON COLUMN participants.pre_questionnaire_data IS 'Pre-negotiation survey responses';
COMMENT ON COLUMN participants.post_questionnaire_data IS 'Post-negotiation survey responses';

-- ============================================
-- 2. SESSIONS TABLE
-- Stores negotiation session metadata
-- ============================================
CREATE TABLE sessions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    session_code TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    status TEXT DEFAULT 'waiting' CHECK (status IN ('waiting', 'active', 'completed', 'cancelled')),
    negotiation_scenario TEXT,
    time_limit_minutes INTEGER DEFAULT 20,
    agreement_reached BOOLEAN,
    final_agreement JSONB DEFAULT '{}'::jsonb
);

ALTER TABLE sessions ADD CONSTRAINT session_code_length CHECK (char_length(session_code) = 6);

COMMENT ON TABLE sessions IS 'Negotiation session metadata and configuration';
COMMENT ON COLUMN sessions.session_code IS '6-character unique code for participants to join';
COMMENT ON COLUMN sessions.status IS 'Session state: waiting, active, completed, or cancelled';
COMMENT ON COLUMN sessions.final_agreement IS 'JSON containing the final negotiated terms if agreement reached';

-- ============================================
-- 3. SESSION_PARTICIPANTS TABLE
-- Junction table linking participants to sessions with roles
-- ============================================
CREATE TABLE session_participants (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    session_id UUID NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    participant_id UUID NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK (role IN ('pm', 'developer')),
    joined_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (session_id, participant_id)
);

COMMENT ON TABLE session_participants IS 'Links participants to sessions with their assigned roles';
COMMENT ON COLUMN session_participants.role IS 'Negotiation role: pm (Project Manager) or developer';

-- ============================================
-- 4. MESSAGES TABLE
-- Stores all chat/negotiation messages
-- ============================================
CREATE TABLE messages (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    session_id UUID NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    participant_id UUID NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    message_type TEXT DEFAULT 'negotiation' CHECK (message_type IN ('negotiation', 'offer', 'acceptance', 'rejection', 'system')),
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    metadata JSONB DEFAULT '{}'::jsonb
);

COMMENT ON TABLE messages IS 'All messages exchanged during negotiation sessions';
COMMENT ON COLUMN messages.message_type IS 'Type of message: negotiation (regular chat), offer, acceptance, rejection, system';
COMMENT ON COLUMN messages.metadata IS 'Additional data like offer details, typing duration, etc.';

-- ============================================
-- 5. ASSISTANT_QUERIES TABLE
-- Logs all AI assistant interactions
-- ============================================
CREATE TABLE assistant_queries (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    session_id UUID NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    participant_id UUID NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
    query_text TEXT NOT NULL,
    response_text TEXT NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    tokens_used INTEGER,
    response_time_ms INTEGER
);

COMMENT ON TABLE assistant_queries IS 'Logs all interactions with the AI negotiation assistant';
COMMENT ON COLUMN assistant_queries.tokens_used IS 'Total tokens (input + output) consumed by this query';
COMMENT ON COLUMN assistant_queries.response_time_ms IS 'API response time in milliseconds';

-- ============================================
-- 6. EVENT_LOG TABLE
-- Comprehensive event tracking for research analysis
-- ============================================
CREATE TABLE event_log (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    session_id UUID REFERENCES sessions(id) ON DELETE CASCADE,
    participant_id UUID REFERENCES participants(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL,
    event_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE event_log IS 'Detailed event log for behavioral analysis';
COMMENT ON COLUMN event_log.event_type IS 'Event types: page_view, button_click, offer_made, message_sent, assistant_opened, etc.';
COMMENT ON COLUMN event_log.event_data IS 'Event-specific data payload';

-- ============================================
-- 7. NEGOTIATION_OUTCOMES TABLE
-- Stores computed outcome metrics for analysis
-- ============================================
CREATE TABLE negotiation_outcomes (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    session_id UUID NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    participant_id UUID NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
    individual_points INTEGER,
    joint_gain INTEGER,
    agreement_rate BOOLEAN,
    time_to_agreement_seconds INTEGER,
    pareto_gap NUMERIC(10, 4),
    behavioral_reliance_score NUMERIC(10, 4),
    query_frequency INTEGER,
    incorporation_score NUMERIC(10, 4),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (session_id, participant_id)
);

COMMENT ON TABLE negotiation_outcomes IS 'Computed negotiation outcome metrics for research analysis';
COMMENT ON COLUMN negotiation_outcomes.individual_points IS 'Points earned by this participant based on payoff matrix';
COMMENT ON COLUMN negotiation_outcomes.joint_gain IS 'Combined points for both participants';
COMMENT ON COLUMN negotiation_outcomes.pareto_gap IS 'Distance from Pareto-optimal outcome (0 = optimal)';
COMMENT ON COLUMN negotiation_outcomes.behavioral_reliance_score IS 'Measure of reliance on AI assistant suggestions';
COMMENT ON COLUMN negotiation_outcomes.query_frequency IS 'Number of AI assistant queries made';
COMMENT ON COLUMN negotiation_outcomes.incorporation_score IS 'Degree to which AI suggestions were incorporated';

-- ============================================
-- INDEXES
-- ============================================

CREATE INDEX idx_sessions_status ON sessions(status);
CREATE INDEX idx_sessions_code ON sessions(session_code);

CREATE INDEX idx_session_participants_session ON session_participants(session_id);
CREATE INDEX idx_session_participants_participant ON session_participants(participant_id);

CREATE INDEX idx_messages_session ON messages(session_id);
CREATE INDEX idx_messages_participant ON messages(participant_id);
CREATE INDEX idx_messages_timestamp ON messages(timestamp);
CREATE INDEX idx_messages_session_timestamp ON messages(session_id, timestamp);

CREATE INDEX idx_assistant_queries_session ON assistant_queries(session_id);
CREATE INDEX idx_assistant_queries_participant ON assistant_queries(participant_id);

CREATE INDEX idx_event_log_session ON event_log(session_id);
CREATE INDEX idx_event_log_participant ON event_log(participant_id);
CREATE INDEX idx_event_log_timestamp ON event_log(timestamp);
CREATE INDEX idx_event_log_type ON event_log(event_type);

CREATE INDEX idx_negotiation_outcomes_session ON negotiation_outcomes(session_id);
CREATE INDEX idx_negotiation_outcomes_participant ON negotiation_outcomes(participant_id);

-- ============================================
-- HELPER FUNCTIONS
-- ============================================

-- Generate a random 6-character session code
CREATE OR REPLACE FUNCTION generate_session_code()
RETURNS TEXT AS $$
DECLARE
    chars TEXT := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
    result TEXT := '';
    i INTEGER;
BEGIN
    FOR i IN 1..6 LOOP
        result := result || substr(chars, floor(random() * length(chars) + 1)::integer, 1);
    END LOOP;
    RETURN result;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION generate_session_code IS 'Generates a random 6-character alphanumeric code (excludes confusing chars like 0, O, 1, I)';

-- Create a new session with auto-generated code
CREATE OR REPLACE FUNCTION create_session(scenario TEXT DEFAULT NULL, time_limit INTEGER DEFAULT 20)
RETURNS sessions AS $$
DECLARE
    new_code TEXT;
    new_session sessions;
BEGIN
    LOOP
        new_code := generate_session_code();
        EXIT WHEN NOT EXISTS (SELECT 1 FROM sessions WHERE session_code = new_code);
    END LOOP;
    
    INSERT INTO sessions (session_code, negotiation_scenario, time_limit_minutes)
    VALUES (new_code, scenario, time_limit)
    RETURNING * INTO new_session;
    
    RETURN new_session;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION create_session IS 'Creates a new session with auto-generated unique code';


-- ============================================================
-- Migration 002: Lab Mode RLS
-- (All RLS policies removed for self-hosted; no-op)
-- ============================================================


-- ============================================================
-- Migration 003: Participant Tokens
-- ============================================================

CREATE TABLE IF NOT EXISTS participant_tokens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    token TEXT UNIQUE NOT NULL,
    session_id UUID REFERENCES sessions(id) ON DELETE CASCADE,
    participant_id UUID REFERENCES participants(id) ON DELETE SET NULL,
    role TEXT CHECK (role IN ('pm', 'developer')),
    terminal_number INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    claimed_at TIMESTAMP WITH TIME ZONE,
    metadata JSONB DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_participant_tokens_token ON participant_tokens(token);
CREATE INDEX IF NOT EXISTS idx_participant_tokens_session ON participant_tokens(session_id);

-- Generate a short, readable token
CREATE OR REPLACE FUNCTION generate_participant_token()
RETURNS TEXT AS $$
DECLARE
    chars TEXT := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
    result TEXT := '';
    i INTEGER;
BEGIN
    FOR i IN 1..5 LOOP
        result := result || substr(chars, floor(random() * length(chars) + 1)::int, 1);
    END LOOP;
    RETURN result;
END;
$$ LANGUAGE plpgsql;

-- Create a batch of tokens for a session (PM + Developer)
CREATE OR REPLACE FUNCTION create_token_batch(
    p_session_id UUID
)
RETURNS TABLE (
    token TEXT,
    role TEXT,
    url TEXT
) AS $$
DECLARE
    new_token TEXT;
    base_url TEXT := '';
BEGIN
    new_token := generate_participant_token();
    INSERT INTO participant_tokens (token, session_id, role)
    VALUES (new_token, p_session_id, 'pm');
    token := new_token;
    role := 'pm';
    url := '/p/' || new_token;
    RETURN NEXT;
    
    new_token := generate_participant_token();
    INSERT INTO participant_tokens (token, session_id, role)
    VALUES (new_token, p_session_id, 'developer');
    token := new_token;
    role := 'developer';
    url := '/p/' || new_token;
    RETURN NEXT;
END;
$$ LANGUAGE plpgsql;


-- ============================================================
-- Migration 004: Session Config
-- ============================================================

ALTER TABLE sessions 
ADD COLUMN IF NOT EXISTS ai_query_limit INTEGER DEFAULT NULL;

ALTER TABLE sessions 
ADD COLUMN IF NOT EXISTS time_extension_minutes INTEGER DEFAULT 0;

COMMENT ON COLUMN sessions.ai_query_limit IS 'Max AI assistant queries per participant when set; NULL means no limit';
COMMENT ON COLUMN sessions.time_extension_minutes IS 'Total time added by admin during active session';

UPDATE sessions 
SET time_extension_minutes = COALESCE(time_extension_minutes, 0)
WHERE time_extension_minutes IS NULL;


-- ============================================================
-- Migration 005: Survey Flow Tracking
-- ============================================================

ALTER TABLE session_participants 
ADD COLUMN IF NOT EXISTS pre_survey_completed_at TIMESTAMPTZ DEFAULT NULL;

CREATE INDEX IF NOT EXISTS idx_session_participants_pre_survey 
ON session_participants(session_id, pre_survey_completed_at);

-- Check if both participants have completed pre-survey
CREATE OR REPLACE FUNCTION check_both_surveys_complete(p_session_id UUID)
RETURNS BOOLEAN AS $$
DECLARE
  total_participants INTEGER;
  completed_surveys INTEGER;
BEGIN
  SELECT COUNT(*), COUNT(pre_survey_completed_at)
  INTO total_participants, completed_surveys
  FROM session_participants
  WHERE session_id = p_session_id;
  
  RETURN total_participants = 2 AND completed_surveys = 2;
END;
$$ LANGUAGE plpgsql;

COMMENT ON COLUMN session_participants.pre_survey_completed_at IS 
  'Timestamp when participant completed the pre-negotiation survey. NULL if not yet completed.';


-- ============================================================
-- Migration 006: Rounds and Completion
-- ============================================================

ALTER TABLE sessions
ADD COLUMN IF NOT EXISTS dyad_id UUID DEFAULT NULL;

ALTER TABLE sessions
ADD COLUMN IF NOT EXISTS round_number INTEGER DEFAULT NULL;

COMMENT ON COLUMN sessions.dyad_id IS 'Shared identifier for the paired participants in this round (same for both in the dyad)';
COMMENT ON COLUMN sessions.round_number IS 'Round index 1, 2, or 3 for multi-round experiments; NULL for legacy single-round sessions';

CREATE INDEX IF NOT EXISTS idx_sessions_dyad_id ON sessions(dyad_id);
CREATE INDEX IF NOT EXISTS idx_sessions_round_number ON sessions(round_number);

ALTER TABLE session_participants
ADD COLUMN IF NOT EXISTS treatment_condition TEXT DEFAULT NULL;

ALTER TABLE session_participants
DROP CONSTRAINT IF EXISTS session_participants_treatment_check;

ALTER TABLE session_participants
ADD CONSTRAINT session_participants_treatment_check
CHECK (treatment_condition IS NULL OR treatment_condition IN ('payoff_always_visible', 'payoff_collapsible'));

COMMENT ON COLUMN session_participants.treatment_condition IS 'A/B: payoff_always_visible or payoff_collapsible for negotiation UI';

CREATE INDEX IF NOT EXISTS idx_session_participants_treatment ON session_participants(treatment_condition);

ALTER TABLE participants
ADD COLUMN IF NOT EXISTS completion_code TEXT DEFAULT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_participants_completion_code ON participants(completion_code) WHERE completion_code IS NOT NULL;

COMMENT ON COLUMN participants.completion_code IS 'Unique code shown after final survey for BEELab payment verification';

ALTER TABLE event_log
ADD COLUMN IF NOT EXISTS round_id UUID DEFAULT NULL;

ALTER TABLE event_log
ADD COLUMN IF NOT EXISTS dyad_id UUID DEFAULT NULL;

COMMENT ON COLUMN event_log.round_id IS 'Session id for the round when event occurred (matches sessions.id for that round)';
COMMENT ON COLUMN event_log.dyad_id IS 'Dyad id for the round when event occurred';

CREATE INDEX IF NOT EXISTS idx_event_log_round_id ON event_log(round_id);
CREATE INDEX IF NOT EXISTS idx_event_log_dyad_id ON event_log(dyad_id);


-- ============================================================
-- Migration 007: Round Queue
-- ============================================================

CREATE TABLE IF NOT EXISTS round_queue (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    participant_id UUID NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
    round_number INTEGER NOT NULL CHECK (round_number >= 1 AND round_number <= 3),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (participant_id, round_number)
);

COMMENT ON TABLE round_queue IS 'Participants waiting to be matched for a given round (1, 2, or 3)';
CREATE INDEX IF NOT EXISTS idx_round_queue_round_number ON round_queue(round_number);
CREATE INDEX IF NOT EXISTS idx_round_queue_participant ON round_queue(participant_id);


-- ============================================================
-- Migration 008: Matchmaking RPC
-- ============================================================

CREATE OR REPLACE FUNCTION try_match_round(p_participant_id UUID, p_round_number INTEGER)
RETURNS TABLE(session_id UUID, session_code TEXT, role TEXT, dyad_id UUID) AS $$
DECLARE
  v_dyad_id UUID;
  v_session_code TEXT;
  v_session_id UUID;
  v_my_role TEXT;
  v_partner_id UUID;
  v_scenario TEXT;
  v_treatment_self TEXT;
  v_treatment_partner TEXT;
BEGIN
  IF p_round_number < 1 OR p_round_number > 3 THEN
    RETURN;
  END IF;

  INSERT INTO round_queue (participant_id, round_number)
  VALUES (p_participant_id, p_round_number)
  ON CONFLICT (participant_id, round_number) DO NOTHING;

  v_scenario := CASE p_round_number
    WHEN 1 THEN 'v1.a'
    WHEN 2 THEN 'v1.b'
    WHEN 3 THEN 'v1.c'
    ELSE 'v1.a'
  END;

  SELECT rq.participant_id INTO v_partner_id
  FROM round_queue rq
  WHERE rq.round_number = p_round_number
    AND rq.participant_id <> p_participant_id
    AND NOT EXISTS (
      SELECT 1
      FROM session_participants sp_me
      JOIN session_participants sp_other ON sp_me.session_id = sp_other.session_id
        AND sp_other.participant_id = rq.participant_id
      JOIN sessions s ON s.id = sp_me.session_id
      WHERE sp_me.participant_id = p_participant_id
        AND s.round_number IS NOT NULL
        AND s.round_number < p_round_number
    )
  LIMIT 1
  FOR UPDATE SKIP LOCKED;

  IF v_partner_id IS NULL THEN
    RETURN;
  END IF;

  v_dyad_id := uuid_generate_v4();

  LOOP
    v_session_code := generate_session_code();
    EXIT WHEN NOT EXISTS (SELECT 1 FROM sessions WHERE sessions.session_code = v_session_code);
  END LOOP;

  INSERT INTO sessions (
    session_code, status, negotiation_scenario, time_limit_minutes,
    dyad_id, round_number
  )
  VALUES (
    v_session_code, 'waiting', v_scenario, 45,
    v_dyad_id, p_round_number
  )
  RETURNING id INTO v_session_id;

  v_my_role := 'pm';
  v_treatment_self := 'payoff_always_visible';
  v_treatment_partner := 'payoff_collapsible';

  INSERT INTO session_participants (session_id, participant_id, role, treatment_condition)
  VALUES
    (v_session_id, p_participant_id, v_my_role, v_treatment_self),
    (v_session_id, v_partner_id, 'developer', v_treatment_partner);

  DELETE FROM round_queue
  WHERE (participant_id = p_participant_id OR participant_id = v_partner_id)
    AND round_number = p_round_number;

  session_id := v_session_id;
  session_code := v_session_code;
  role := v_my_role;
  dyad_id := v_dyad_id;
  RETURN NEXT;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION try_match_round IS 'Attempt to match participant for round N; returns session and role if matched, else no row';


-- ============================================================
-- Migration 009: Pair-Based Rounds
-- ============================================================

ALTER TABLE sessions
ADD COLUMN IF NOT EXISTS pair_session_id UUID DEFAULT NULL;

ALTER TABLE sessions
ADD CONSTRAINT fk_sessions_pair_session
FOREIGN KEY (pair_session_id) REFERENCES sessions(id) ON DELETE SET NULL;

COMMENT ON COLUMN sessions.pair_session_id IS 'Links round session to the pair/join session where participants did pre-survey';

CREATE INDEX IF NOT EXISTS idx_sessions_pair_session_id ON sessions(pair_session_id);

ALTER TABLE participants
ADD COLUMN IF NOT EXISTS post_round_survey_data JSONB DEFAULT '{}'::jsonb;

COMMENT ON COLUMN participants.post_round_survey_data IS 'Post-round survey responses keyed by round: {"1":{"opponent_priority_guess":"I2"},"2":{...},"3":{...}}';

-- Creates a round session for the pair; same 2 participants, roles preserved
CREATE OR REPLACE FUNCTION create_round_for_pair(p_pair_session_id UUID, p_round_number INTEGER)
RETURNS UUID AS $$
DECLARE
  v_dyad_id UUID;
  v_session_code TEXT;
  v_session_id UUID;
  v_scenario TEXT;
  v_participant1_id UUID;
  v_participant2_id UUID;
  v_role1 TEXT;
  v_role2 TEXT;
  v_treatment1 TEXT;
  v_treatment2 TEXT;
BEGIN
  IF p_round_number < 1 OR p_round_number > 3 THEN
    RAISE EXCEPTION 'round_number must be 1, 2, or 3';
  END IF;

  SELECT participant_id, role
  INTO v_participant1_id, v_role1
  FROM session_participants
  WHERE session_id = p_pair_session_id
  ORDER BY joined_at ASC
  LIMIT 1;

  SELECT participant_id, role
  INTO v_participant2_id, v_role2
  FROM session_participants
  WHERE session_id = p_pair_session_id
  ORDER BY joined_at ASC
  OFFSET 1 LIMIT 1;

  IF v_participant1_id IS NULL OR v_participant2_id IS NULL THEN
    RAISE EXCEPTION 'Pair session must have exactly 2 participants';
  END IF;

  v_scenario := CASE p_round_number
    WHEN 1 THEN 'v1.a'
    WHEN 2 THEN 'v1.b'
    WHEN 3 THEN 'v1.c'
    ELSE 'v1.a'
  END;

  v_dyad_id := uuid_generate_v4();

  LOOP
    v_session_code := generate_session_code();
    EXIT WHEN NOT EXISTS (SELECT 1 FROM sessions WHERE sessions.session_code = v_session_code);
  END LOOP;

  v_treatment1 := 'payoff_always_visible';
  v_treatment2 := 'payoff_collapsible';

  INSERT INTO sessions (
    session_code, status, negotiation_scenario, time_limit_minutes,
    dyad_id, round_number, pair_session_id
  )
  VALUES (
    v_session_code, 'waiting', v_scenario, 45,
    v_dyad_id, p_round_number, p_pair_session_id
  )
  RETURNING id INTO v_session_id;

  INSERT INTO session_participants (session_id, participant_id, role, treatment_condition)
  VALUES
    (v_session_id, v_participant1_id, COALESCE(v_role1, 'pm'), v_treatment1),
    (v_session_id, v_participant2_id, COALESCE(v_role2, 'developer'), v_treatment2);

  RETURN v_session_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION create_round_for_pair IS 'Creates a round session for a pair; same 2 participants, payoff v1.a/b/c by round';


-- ============================================================
-- Migration 010: Experiment Batches
-- ============================================================

CREATE TABLE IF NOT EXISTS experiment_batches (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    batch_code TEXT UNIQUE NOT NULL,
    max_participants INTEGER NOT NULL DEFAULT 20,
    status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE experiment_batches IS 'Batch (experiment run) for pool-based matchmaking; up to 20 participants per batch';
COMMENT ON COLUMN experiment_batches.batch_code IS '6-char code participants enter to join the batch';

CREATE UNIQUE INDEX IF NOT EXISTS idx_experiment_batches_batch_code ON experiment_batches(batch_code);

CREATE TABLE IF NOT EXISTS batch_participants (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    batch_id UUID NOT NULL REFERENCES experiment_batches(id) ON DELETE CASCADE,
    participant_id UUID NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
    condition_order JSONB NOT NULL,
    joined_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (batch_id, participant_id)
);

COMMENT ON TABLE batch_participants IS 'Participants in a batch with assigned condition order (permutation of v1.a, v1.b, v1.c)';
COMMENT ON COLUMN batch_participants.condition_order IS 'JSON array of 3 scenario keys, e.g. ["v1.a","v1.b","v1.c"] for Round A then B then C';

CREATE INDEX IF NOT EXISTS idx_batch_participants_batch_id ON batch_participants(batch_id);
CREATE INDEX IF NOT EXISTS idx_batch_participants_participant_id ON batch_participants(participant_id);

-- Create a new experiment batch with unique 6-char code
CREATE OR REPLACE FUNCTION create_batch(p_max_participants INTEGER DEFAULT 20)
RETURNS experiment_batches AS $$
DECLARE
    v_batch_code TEXT;
    v_batch experiment_batches;
BEGIN
    LOOP
        v_batch_code := generate_session_code();
        EXIT WHEN NOT EXISTS (SELECT 1 FROM sessions WHERE session_code = v_batch_code)
          AND NOT EXISTS (SELECT 1 FROM experiment_batches WHERE batch_code = v_batch_code);
    END LOOP;

    INSERT INTO experiment_batches (batch_code, max_participants, status)
    VALUES (v_batch_code, p_max_participants, 'open')
    RETURNING * INTO v_batch;
    RETURN v_batch;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION create_batch IS 'Creates a new experiment batch with unique 6-char code';

-- Pool matchmaking: pairs two participants in same batch, same condition, no past opponent
CREATE OR REPLACE FUNCTION try_match_pool_round(p_participant_id UUID, p_slot_index INTEGER)
RETURNS TABLE(session_id UUID, session_code TEXT, role TEXT, dyad_id UUID) AS $$
DECLARE
    v_batch_id UUID;
    v_my_condition TEXT;
    v_partner_id UUID;
    v_dyad_id UUID;
    v_session_code TEXT;
    v_session_id UUID;
    v_my_role TEXT;
    v_treatment_self TEXT;
    v_treatment_partner TEXT;
BEGIN
    IF p_slot_index < 1 OR p_slot_index > 3 THEN
        RETURN;
    END IF;

    SELECT bp.batch_id,
           bp.condition_order->>(p_slot_index - 1) INTO v_batch_id, v_my_condition
    FROM batch_participants bp
    WHERE bp.participant_id = p_participant_id
    LIMIT 1;

    IF v_batch_id IS NULL OR v_my_condition IS NULL OR v_my_condition = '' THEN
        RETURN;
    END IF;

    INSERT INTO round_queue (participant_id, round_number)
    VALUES (p_participant_id, p_slot_index)
    ON CONFLICT (participant_id, round_number) DO NOTHING;

    SELECT rq.participant_id INTO v_partner_id
    FROM round_queue rq
    JOIN batch_participants bp ON bp.participant_id = rq.participant_id AND bp.batch_id = v_batch_id
    WHERE rq.round_number = p_slot_index
      AND rq.participant_id <> p_participant_id
      AND (bp.condition_order->>(p_slot_index - 1)) = v_my_condition
      AND NOT EXISTS (
          SELECT 1
          FROM session_participants sp_me
          JOIN session_participants sp_other ON sp_me.session_id = sp_other.session_id
            AND sp_other.participant_id = rq.participant_id
          JOIN sessions s ON s.id = sp_me.session_id
          WHERE sp_me.participant_id = p_participant_id
            AND s.round_number IS NOT NULL
            AND s.round_number < p_slot_index
      )
    LIMIT 1
    FOR UPDATE OF rq SKIP LOCKED;

    IF v_partner_id IS NULL THEN
        RETURN;
    END IF;

    v_dyad_id := uuid_generate_v4();

    LOOP
        v_session_code := generate_session_code();
        EXIT WHEN NOT EXISTS (SELECT 1 FROM sessions WHERE sessions.session_code = v_session_code)
          AND NOT EXISTS (SELECT 1 FROM experiment_batches WHERE batch_code = v_session_code);
    END LOOP;

    INSERT INTO sessions (
        session_code, status, negotiation_scenario, time_limit_minutes,
        dyad_id, round_number
    )
    VALUES (
        v_session_code, 'waiting', v_my_condition, 45,
        v_dyad_id, p_slot_index
    )
    RETURNING id INTO v_session_id;

    v_my_role := 'pm';
    v_treatment_self := 'payoff_always_visible';
    v_treatment_partner := 'payoff_collapsible';

    INSERT INTO session_participants (session_id, participant_id, role, treatment_condition)
    VALUES
        (v_session_id, p_participant_id, v_my_role, v_treatment_self),
        (v_session_id, v_partner_id, 'developer', v_treatment_partner);

    DELETE FROM round_queue
    WHERE (participant_id = p_participant_id OR participant_id = v_partner_id)
      AND round_number = p_slot_index;

    session_id := v_session_id;
    session_code := v_session_code;
    role := v_my_role;
    dyad_id := v_dyad_id;
    RETURN NEXT;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION try_match_pool_round IS 'Pool matchmaking: match by (slot, condition), no past opponent; returns session and role if matched';


-- ============================================================
-- Migration 011: Round Timer and Ready Lobby
-- 10 min per round (was 45); add briefing_ready_at for "both ready" lobby
-- ============================================================

ALTER TABLE session_participants
ADD COLUMN IF NOT EXISTS briefing_ready_at TIMESTAMPTZ DEFAULT NULL;

COMMENT ON COLUMN session_participants.briefing_ready_at IS 'When participant clicked ready after briefing; both must be set before round timer starts';

CREATE INDEX IF NOT EXISTS idx_session_participants_briefing_ready
ON session_participants(session_id, briefing_ready_at);

-- try_match_pool_round — updated to 10 min per round
CREATE OR REPLACE FUNCTION try_match_pool_round(p_participant_id UUID, p_slot_index INTEGER)
RETURNS TABLE(session_id UUID, session_code TEXT, role TEXT, dyad_id UUID) AS $$
DECLARE
    v_batch_id UUID;
    v_my_condition TEXT;
    v_partner_id UUID;
    v_dyad_id UUID;
    v_session_code TEXT;
    v_session_id UUID;
    v_my_role TEXT;
    v_treatment_self TEXT;
    v_treatment_partner TEXT;
BEGIN
    IF p_slot_index < 1 OR p_slot_index > 3 THEN
        RETURN;
    END IF;

    SELECT bp.batch_id,
           bp.condition_order->>(p_slot_index - 1) INTO v_batch_id, v_my_condition
    FROM batch_participants bp
    WHERE bp.participant_id = p_participant_id
    LIMIT 1;

    IF v_batch_id IS NULL OR v_my_condition IS NULL OR v_my_condition = '' THEN
        RETURN;
    END IF;

    INSERT INTO round_queue (participant_id, round_number)
    VALUES (p_participant_id, p_slot_index)
    ON CONFLICT (participant_id, round_number) DO NOTHING;

    SELECT rq.participant_id INTO v_partner_id
    FROM round_queue rq
    JOIN batch_participants bp ON bp.participant_id = rq.participant_id AND bp.batch_id = v_batch_id
    WHERE rq.round_number = p_slot_index
      AND rq.participant_id <> p_participant_id
      AND (bp.condition_order->>(p_slot_index - 1)) = v_my_condition
      AND NOT EXISTS (
          SELECT 1
          FROM session_participants sp_me
          JOIN session_participants sp_other ON sp_me.session_id = sp_other.session_id
            AND sp_other.participant_id = rq.participant_id
          JOIN sessions s ON s.id = sp_me.session_id
          WHERE sp_me.participant_id = p_participant_id
            AND s.round_number IS NOT NULL
            AND s.round_number < p_slot_index
      )
    LIMIT 1
    FOR UPDATE OF rq SKIP LOCKED;

    IF v_partner_id IS NULL THEN
        RETURN;
    END IF;

    v_dyad_id := uuid_generate_v4();

    LOOP
        v_session_code := generate_session_code();
        EXIT WHEN NOT EXISTS (SELECT 1 FROM sessions WHERE sessions.session_code = v_session_code)
          AND NOT EXISTS (SELECT 1 FROM experiment_batches WHERE batch_code = v_session_code);
    END LOOP;

    INSERT INTO sessions (
        session_code, status, negotiation_scenario, time_limit_minutes,
        dyad_id, round_number
    )
    VALUES (
        v_session_code, 'waiting', v_my_condition, 10,
        v_dyad_id, p_slot_index
    )
    RETURNING id INTO v_session_id;

    v_my_role := 'pm';
    v_treatment_self := 'payoff_always_visible';
    v_treatment_partner := 'payoff_collapsible';

    INSERT INTO session_participants (session_id, participant_id, role, treatment_condition)
    VALUES
        (v_session_id, p_participant_id, v_my_role, v_treatment_self),
        (v_session_id, v_partner_id, 'developer', v_treatment_partner);

    DELETE FROM round_queue
    WHERE (participant_id = p_participant_id OR participant_id = v_partner_id)
      AND round_number = p_slot_index;

    session_id := v_session_id;
    session_code := v_session_code;
    role := v_my_role;
    dyad_id := v_dyad_id;
    RETURN NEXT;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION try_match_pool_round IS 'Pool matchmaking: 10 min per round; match by (slot, condition), no past opponent';

-- create_round_for_pair — updated to 10 min per round
CREATE OR REPLACE FUNCTION create_round_for_pair(p_pair_session_id UUID, p_round_number INTEGER)
RETURNS UUID AS $$
DECLARE
  v_dyad_id UUID;
  v_session_code TEXT;
  v_session_id UUID;
  v_scenario TEXT;
  v_participant1_id UUID;
  v_participant2_id UUID;
  v_role1 TEXT;
  v_role2 TEXT;
  v_treatment1 TEXT;
  v_treatment2 TEXT;
BEGIN
  IF p_round_number < 1 OR p_round_number > 3 THEN
    RAISE EXCEPTION 'round_number must be 1, 2, or 3';
  END IF;

  SELECT participant_id, role
  INTO v_participant1_id, v_role1
  FROM session_participants
  WHERE session_id = p_pair_session_id
  ORDER BY joined_at ASC
  LIMIT 1;

  SELECT participant_id, role
  INTO v_participant2_id, v_role2
  FROM session_participants
  WHERE session_id = p_pair_session_id
  ORDER BY joined_at ASC
  OFFSET 1 LIMIT 1;

  IF v_participant1_id IS NULL OR v_participant2_id IS NULL THEN
    RAISE EXCEPTION 'Pair session must have exactly 2 participants';
  END IF;

  v_scenario := CASE p_round_number
    WHEN 1 THEN 'v1.a'
    WHEN 2 THEN 'v1.b'
    WHEN 3 THEN 'v1.c'
    ELSE 'v1.a'
  END;

  v_dyad_id := uuid_generate_v4();

  LOOP
    v_session_code := generate_session_code();
    EXIT WHEN NOT EXISTS (SELECT 1 FROM sessions WHERE sessions.session_code = v_session_code);
  END LOOP;

  v_treatment1 := 'payoff_always_visible';
  v_treatment2 := 'payoff_collapsible';

  INSERT INTO sessions (
    session_code, status, negotiation_scenario, time_limit_minutes,
    dyad_id, round_number, pair_session_id
  )
  VALUES (
    v_session_code, 'waiting', v_scenario, 10,
    v_dyad_id, p_round_number, p_pair_session_id
  )
  RETURNING id INTO v_session_id;

  INSERT INTO session_participants (session_id, participant_id, role, treatment_condition)
  VALUES
    (v_session_id, v_participant1_id, COALESCE(v_role1, 'pm'), v_treatment1),
    (v_session_id, v_participant2_id, COALESCE(v_role2, 'developer'), v_treatment2);

  RETURN v_session_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION create_round_for_pair IS 'Creates a round session for a pair; 10 min per round, payoff v1.a/b/c by round';


-- ============================================================
-- Migration 012: Batch Matchmaking (match_batch_for_round)
-- ============================================================

-- Batch matchmaking: match all queued participants for a round
CREATE OR REPLACE FUNCTION match_batch_for_round(p_batch_id UUID, p_slot_index INTEGER)
RETURNS INTEGER AS $$
DECLARE
    v_condition TEXT;
    v_sessions_created INTEGER := 0;
    v_participant_id UUID;
    v_partner_id UUID;
BEGIN
    IF p_slot_index < 1 OR p_slot_index > 3 THEN
        RAISE EXCEPTION 'slot_index must be 1, 2, or 3';
    END IF;

    CREATE TEMP TABLE IF NOT EXISTS batch_match_queued (
        participant_id UUID PRIMARY KEY,
        condition TEXT NOT NULL
    );
    DELETE FROM batch_match_queued WHERE TRUE;

    INSERT INTO batch_match_queued (participant_id, condition)
    SELECT rq.participant_id, (bp.condition_order->>(p_slot_index - 1))::TEXT
    FROM round_queue rq
    JOIN batch_participants bp ON bp.participant_id = rq.participant_id AND bp.batch_id = p_batch_id
    WHERE rq.round_number = p_slot_index
    FOR UPDATE OF rq;

    CREATE TEMP TABLE IF NOT EXISTS batch_match_remaining (
        participant_id UUID PRIMARY KEY
    );

    FOR v_condition IN SELECT DISTINCT condition FROM batch_match_queued
    LOOP
        DELETE FROM batch_match_remaining WHERE TRUE;
        INSERT INTO batch_match_remaining (participant_id)
        SELECT participant_id FROM batch_match_queued WHERE condition = v_condition;

        WHILE (SELECT COUNT(*) FROM batch_match_remaining) > 0 LOOP
            SELECT r.participant_id INTO v_participant_id
            FROM batch_match_remaining r
            ORDER BY (
                SELECT COUNT(*)
                FROM batch_match_remaining r2
                WHERE r2.participant_id <> r.participant_id
                  AND NOT EXISTS (
                      SELECT 1
                      FROM session_participants sp1
                      JOIN session_participants sp2 ON sp1.session_id = sp2.session_id AND sp2.participant_id = r2.participant_id
                      JOIN sessions s ON s.id = sp1.session_id
                      WHERE sp1.participant_id = r.participant_id
                        AND s.round_number IS NOT NULL
                        AND s.round_number < p_slot_index
                  )
            ), r.participant_id
            LIMIT 1;

            IF v_participant_id IS NULL THEN
                RAISE EXCEPTION 'match_batch_for_round: no participant in remaining (logic error)';
            END IF;

            SELECT r2.participant_id INTO v_partner_id
            FROM batch_match_remaining r2
            WHERE r2.participant_id <> v_participant_id
              AND NOT EXISTS (
                  SELECT 1
                  FROM session_participants sp1
                  JOIN session_participants sp2 ON sp1.session_id = sp2.session_id AND sp2.participant_id = r2.participant_id
                  JOIN sessions s ON s.id = sp1.session_id
                  WHERE sp1.participant_id = v_participant_id
                    AND s.round_number IS NOT NULL
                    AND s.round_number < p_slot_index
              )
            ORDER BY r2.participant_id
            LIMIT 1;

            IF v_partner_id IS NULL THEN
                RAISE EXCEPTION 'match_batch_for_round: no valid partner for participant % in condition % (odd bucket or past-opponent deadlock)',
                    v_participant_id, v_condition;
            END IF;

            PERFORM create_one_pool_session(v_participant_id, v_partner_id, p_slot_index, v_condition);

            v_sessions_created := v_sessions_created + 1;

            DELETE FROM round_queue
            WHERE participant_id IN (v_participant_id, v_partner_id) AND round_number = p_slot_index;

            DELETE FROM batch_match_remaining
            WHERE participant_id IN (v_participant_id, v_partner_id);
        END LOOP;
    END LOOP;

    RETURN v_sessions_created;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION match_batch_for_round IS 'Batch matchmaking: match all queued participants for a round (same condition, no past opponent); returns sessions created';

-- Helper: create one pool session for two participants
CREATE OR REPLACE FUNCTION create_one_pool_session(
    p_participant_id UUID,
    p_partner_id UUID,
    p_slot_index INTEGER,
    p_condition TEXT
) RETURNS UUID AS $$
DECLARE
    v_dyad_id UUID;
    v_session_code TEXT;
    v_session_id UUID;
BEGIN
    v_dyad_id := uuid_generate_v4();

    LOOP
        v_session_code := generate_session_code();
        EXIT WHEN NOT EXISTS (SELECT 1 FROM sessions WHERE session_code = v_session_code)
          AND NOT EXISTS (SELECT 1 FROM experiment_batches WHERE batch_code = v_session_code);
    END LOOP;

    INSERT INTO sessions (
        session_code, status, negotiation_scenario, time_limit_minutes,
        dyad_id, round_number
    )
    VALUES (
        v_session_code, 'waiting', p_condition, 10,
        v_dyad_id, p_slot_index
    )
    RETURNING id INTO v_session_id;

    INSERT INTO session_participants (session_id, participant_id, role, treatment_condition)
    VALUES
        (v_session_id, p_participant_id, 'pm', 'payoff_always_visible'),
        (v_session_id, p_partner_id, 'developer', 'payoff_collapsible');

    RETURN v_session_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION create_one_pool_session IS 'Creates one pool round session for two participants; used by match_batch_for_round';


-- ============================================================
-- Migration 013: Batch Round Queue Counts
-- ============================================================

CREATE OR REPLACE FUNCTION get_batch_round_queue_counts(p_batch_ids UUID[])
RETURNS TABLE(batch_id UUID, round_number INTEGER, queue_count BIGINT) AS $$
BEGIN
    RETURN QUERY
    SELECT bp.batch_id,
           rq.round_number::INTEGER,
           COUNT(*)::BIGINT
    FROM round_queue rq
    JOIN batch_participants bp ON bp.participant_id = rq.participant_id
    WHERE bp.batch_id = ANY(p_batch_ids)
      AND rq.round_number BETWEEN 1 AND 3
    GROUP BY bp.batch_id, rq.round_number;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER STABLE;

COMMENT ON FUNCTION get_batch_round_queue_counts IS 'Returns queue counts per (batch_id, round_number) for admin and auto-match';


-- ============================================================
-- Migration 014: Clear Batches and Round Sessions
-- ============================================================

CREATE OR REPLACE FUNCTION clear_all_batches_and_round_sessions()
RETURNS TABLE(sessions_deleted BIGINT, queue_deleted BIGINT, batches_deleted BIGINT) AS $$
DECLARE
    v_sessions BIGINT;
    v_queue BIGINT;
    v_batches BIGINT;
BEGIN
    WITH deleted AS (
        DELETE FROM sessions WHERE round_number IS NOT NULL RETURNING id
    )
    SELECT COUNT(*)::BIGINT INTO v_sessions FROM deleted;

    WITH deleted AS (
        DELETE FROM round_queue WHERE TRUE RETURNING id
    )
    SELECT COUNT(*)::BIGINT INTO v_queue FROM deleted;

    WITH deleted AS (
        DELETE FROM experiment_batches WHERE TRUE RETURNING id
    )
    SELECT COUNT(*)::BIGINT INTO v_batches FROM deleted;

    sessions_deleted := v_sessions;
    queue_deleted := v_queue;
    batches_deleted := v_batches;
    RETURN NEXT;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION clear_all_batches_and_round_sessions IS 'Cleanup: remove all batches, round sessions, and round queue for a fresh start. Leaves participants and non-round sessions intact.';


-- ============================================================
-- Migration 015: Match Batch - Odd Bucket and Guard
-- Excludes already-matched; leaves odd-condition participants in queue
-- ============================================================

CREATE OR REPLACE FUNCTION match_batch_for_round(p_batch_id UUID, p_slot_index INTEGER)
RETURNS INTEGER AS $$
DECLARE
    v_condition TEXT;
    v_sessions_created INTEGER := 0;
    v_participant_id UUID;
    v_partner_id UUID;
BEGIN
    IF p_slot_index < 1 OR p_slot_index > 3 THEN
        RAISE EXCEPTION 'slot_index must be 1, 2, or 3';
    END IF;

    CREATE TEMP TABLE IF NOT EXISTS batch_match_queued (
        participant_id UUID PRIMARY KEY,
        condition TEXT NOT NULL
    );
    DELETE FROM batch_match_queued WHERE TRUE;

    INSERT INTO batch_match_queued (participant_id, condition)
    SELECT rq.participant_id, (bp.condition_order->>(p_slot_index - 1))::TEXT
    FROM round_queue rq
    JOIN batch_participants bp ON bp.participant_id = rq.participant_id AND bp.batch_id = p_batch_id
    WHERE rq.round_number = p_slot_index
      AND NOT EXISTS (
          SELECT 1
          FROM session_participants sp
          JOIN sessions s ON s.id = sp.session_id
          WHERE sp.participant_id = rq.participant_id
            AND s.round_number = p_slot_index
      )
    FOR UPDATE OF rq;

    CREATE TEMP TABLE IF NOT EXISTS batch_match_remaining (
        participant_id UUID PRIMARY KEY
    );

    FOR v_condition IN SELECT DISTINCT condition FROM batch_match_queued
    LOOP
        DELETE FROM batch_match_remaining WHERE TRUE;
        INSERT INTO batch_match_remaining (participant_id)
        SELECT participant_id FROM batch_match_queued WHERE condition = v_condition;

        WHILE (SELECT COUNT(*) FROM batch_match_remaining) > 0 LOOP
            SELECT r.participant_id INTO v_participant_id
            FROM batch_match_remaining r
            ORDER BY (
                SELECT COUNT(*)
                FROM batch_match_remaining r2
                WHERE r2.participant_id <> r.participant_id
                  AND NOT EXISTS (
                      SELECT 1
                      FROM session_participants sp1
                      JOIN session_participants sp2 ON sp1.session_id = sp2.session_id AND sp2.participant_id = r2.participant_id
                      JOIN sessions s ON s.id = sp1.session_id
                      WHERE sp1.participant_id = r.participant_id
                        AND s.round_number IS NOT NULL
                        AND s.round_number < p_slot_index
                  )
            ), r.participant_id
            LIMIT 1;

            IF v_participant_id IS NULL THEN
                EXIT;
            END IF;

            SELECT r2.participant_id INTO v_partner_id
            FROM batch_match_remaining r2
            WHERE r2.participant_id <> v_participant_id
              AND NOT EXISTS (
                  SELECT 1
                  FROM session_participants sp1
                  JOIN session_participants sp2 ON sp1.session_id = sp2.session_id AND sp2.participant_id = r2.participant_id
                  JOIN sessions s ON s.id = sp1.session_id
                  WHERE sp1.participant_id = v_participant_id
                    AND s.round_number IS NOT NULL
                    AND s.round_number < p_slot_index
              )
            ORDER BY r2.participant_id
            LIMIT 1;

            IF v_partner_id IS NULL THEN
                DELETE FROM batch_match_remaining WHERE participant_id = v_participant_id;
                CONTINUE;
            END IF;

            PERFORM create_one_pool_session(v_participant_id, v_partner_id, p_slot_index, v_condition);
            v_sessions_created := v_sessions_created + 1;

            DELETE FROM round_queue
            WHERE participant_id IN (v_participant_id, v_partner_id) AND round_number = p_slot_index;

            DELETE FROM batch_match_remaining
            WHERE participant_id IN (v_participant_id, v_partner_id);
        END LOOP;
    END LOOP;

    RETURN v_sessions_created;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION match_batch_for_round IS 'Batch matchmaking: match queued participants for a round (same condition, no past opponent). Skips already-matched; leaves odd-condition participants in queue instead of failing.';


-- ============================================================
-- Migration 016: Join Batch Atomic
-- Atomic batch join with paired condition assignment
-- ============================================================

CREATE OR REPLACE FUNCTION join_batch_atomic(p_batch_id UUID, p_participant_id UUID)
RETURNS batch_participants AS $$
DECLARE
    v_batch experiment_batches;
    v_count INTEGER;
    v_perm_index INTEGER;
    v_condition_order JSONB;
    v_row batch_participants;
BEGIN
    SELECT * INTO v_batch
    FROM experiment_batches
    WHERE id = p_batch_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Batch not found';
    END IF;
    IF v_batch.status <> 'open' THEN
        RAISE EXCEPTION 'Batch is not open for joining';
    END IF;

    SELECT * INTO v_row
    FROM batch_participants
    WHERE batch_id = p_batch_id AND participant_id = p_participant_id;
    IF FOUND THEN
        RETURN v_row;
    END IF;

    v_count := (SELECT count(*)::INTEGER FROM batch_participants WHERE batch_id = p_batch_id);
    IF v_count >= v_batch.max_participants THEN
        RAISE EXCEPTION 'Batch is full';
    END IF;

    v_perm_index := (v_count / 2) % 6;

    v_condition_order := CASE v_perm_index
        WHEN 0 THEN '["v1.a","v1.b","v1.c"]'::JSONB
        WHEN 1 THEN '["v1.a","v1.c","v1.b"]'::JSONB
        WHEN 2 THEN '["v1.b","v1.a","v1.c"]'::JSONB
        WHEN 3 THEN '["v1.b","v1.c","v1.a"]'::JSONB
        WHEN 4 THEN '["v1.c","v1.a","v1.b"]'::JSONB
        ELSE '["v1.c","v1.b","v1.a"]'::JSONB
    END;

    INSERT INTO batch_participants (batch_id, participant_id, condition_order)
    VALUES (p_batch_id, p_participant_id, v_condition_order)
    RETURNING * INTO v_row;

    RETURN v_row;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION join_batch_atomic IS 'Atomic batch join: assigns condition order in pairs so every round has even condition counts; prevents one participant left waiting when many join at once.';


-- ============================================================
-- Migration 017: Match Batch Cross-Condition Pair
-- Pairs remaining 2 from different conditions so no one waits
-- ============================================================

CREATE OR REPLACE FUNCTION match_batch_for_round(p_batch_id UUID, p_slot_index INTEGER)
RETURNS INTEGER AS $$
DECLARE
    v_condition TEXT;
    v_sessions_created INTEGER := 0;
    v_participant_id UUID;
    v_partner_id UUID;
    v_remain_count INTEGER;
    v_p1_id UUID;
    v_p2_id UUID;
    v_p1_condition TEXT;
BEGIN
    IF p_slot_index < 1 OR p_slot_index > 3 THEN
        RAISE EXCEPTION 'slot_index must be 1, 2, or 3';
    END IF;

    CREATE TEMP TABLE IF NOT EXISTS batch_match_queued (
        participant_id UUID PRIMARY KEY,
        condition TEXT NOT NULL
    );
    DELETE FROM batch_match_queued WHERE TRUE;

    INSERT INTO batch_match_queued (participant_id, condition)
    SELECT rq.participant_id, (bp.condition_order->>(p_slot_index - 1))::TEXT
    FROM round_queue rq
    JOIN batch_participants bp ON bp.participant_id = rq.participant_id AND bp.batch_id = p_batch_id
    WHERE rq.round_number = p_slot_index
      AND NOT EXISTS (
          SELECT 1
          FROM session_participants sp
          JOIN sessions s ON s.id = sp.session_id
          WHERE sp.participant_id = rq.participant_id
            AND s.round_number = p_slot_index
      )
    FOR UPDATE OF rq;

    CREATE TEMP TABLE IF NOT EXISTS batch_match_remaining (
        participant_id UUID PRIMARY KEY
    );

    FOR v_condition IN SELECT DISTINCT condition FROM batch_match_queued
    LOOP
        DELETE FROM batch_match_remaining WHERE TRUE;
        INSERT INTO batch_match_remaining (participant_id)
        SELECT participant_id FROM batch_match_queued WHERE condition = v_condition;

        WHILE (SELECT COUNT(*) FROM batch_match_remaining) > 0 LOOP
            SELECT r.participant_id INTO v_participant_id
            FROM batch_match_remaining r
            ORDER BY (
                SELECT COUNT(*)
                FROM batch_match_remaining r2
                WHERE r2.participant_id <> r.participant_id
                  AND NOT EXISTS (
                      SELECT 1
                      FROM session_participants sp1
                      JOIN session_participants sp2 ON sp1.session_id = sp2.session_id AND sp2.participant_id = r2.participant_id
                      JOIN sessions s ON s.id = sp1.session_id
                      WHERE sp1.participant_id = r.participant_id
                        AND s.round_number IS NOT NULL
                        AND s.round_number < p_slot_index
                  )
            ), r.participant_id
            LIMIT 1;

            IF v_participant_id IS NULL THEN
                EXIT;
            END IF;

            SELECT r2.participant_id INTO v_partner_id
            FROM batch_match_remaining r2
            WHERE r2.participant_id <> v_participant_id
              AND NOT EXISTS (
                  SELECT 1
                  FROM session_participants sp1
                  JOIN session_participants sp2 ON sp1.session_id = sp2.session_id AND sp2.participant_id = r2.participant_id
                  JOIN sessions s ON s.id = sp1.session_id
                  WHERE sp1.participant_id = v_participant_id
                    AND s.round_number IS NOT NULL
                    AND s.round_number < p_slot_index
              )
            ORDER BY r2.participant_id
            LIMIT 1;

            IF v_partner_id IS NULL THEN
                DELETE FROM batch_match_remaining WHERE participant_id = v_participant_id;
                CONTINUE;
            END IF;

            PERFORM create_one_pool_session(v_participant_id, v_partner_id, p_slot_index, v_condition);
            v_sessions_created := v_sessions_created + 1;

            DELETE FROM round_queue
            WHERE participant_id IN (v_participant_id, v_partner_id) AND round_number = p_slot_index;

            DELETE FROM batch_match_remaining
            WHERE participant_id IN (v_participant_id, v_partner_id);
        END LOOP;
    END LOOP;

    -- Cross-condition pair: if exactly 2 remain in queue for this batch+round, pair them
    SELECT count(*)::INTEGER INTO v_remain_count
    FROM round_queue rq
    JOIN batch_participants bp ON bp.participant_id = rq.participant_id AND bp.batch_id = p_batch_id
    WHERE rq.round_number = p_slot_index;

    IF v_remain_count = 2 THEN
        SELECT rq.participant_id, (bp.condition_order->>(p_slot_index - 1))::TEXT
        INTO v_p1_id, v_p1_condition
        FROM round_queue rq
        JOIN batch_participants bp ON bp.participant_id = rq.participant_id AND bp.batch_id = p_batch_id
        WHERE rq.round_number = p_slot_index
        ORDER BY rq.participant_id
        LIMIT 1;

        SELECT rq.participant_id INTO v_p2_id
        FROM round_queue rq
        JOIN batch_participants bp ON bp.participant_id = rq.participant_id AND bp.batch_id = p_batch_id
        WHERE rq.round_number = p_slot_index AND rq.participant_id <> v_p1_id
        LIMIT 1;

        IF v_p2_id IS NOT NULL AND NOT EXISTS (
            SELECT 1
            FROM session_participants sp1
            JOIN session_participants sp2 ON sp1.session_id = sp2.session_id AND sp2.participant_id = v_p2_id
            JOIN sessions s ON s.id = sp1.session_id
            WHERE sp1.participant_id = v_p1_id
              AND s.round_number IS NOT NULL
              AND s.round_number < p_slot_index
        ) THEN
            PERFORM create_one_pool_session(v_p1_id, v_p2_id, p_slot_index, v_p1_condition);
            v_sessions_created := v_sessions_created + 1;
            DELETE FROM round_queue
            WHERE participant_id IN (v_p1_id, v_p2_id) AND round_number = p_slot_index;
        END IF;
    END IF;

    RETURN v_sessions_created;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION match_batch_for_round IS 'Batch matchmaking: same-condition pairs first; if exactly 2 remain (odd from different conditions), pair them in one cross-condition session so no one is left waiting.';


-- ============================================================
-- Migration 018: Pre-Seeded Round Schedule
-- ============================================================

CREATE TABLE IF NOT EXISTS batch_round_assignments (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    batch_id UUID NOT NULL REFERENCES experiment_batches(id) ON DELETE CASCADE,
    round_number INTEGER NOT NULL CHECK (round_number >= 1 AND round_number <= 3),
    participant_id_1 UUID NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
    participant_id_2 UUID NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
    CONSTRAINT batch_round_assignments_order CHECK (participant_id_1 < participant_id_2),
    UNIQUE (batch_id, round_number, participant_id_1),
    UNIQUE (batch_id, round_number, participant_id_2)
);

COMMENT ON TABLE batch_round_assignments IS 'Pre-seeded round schedule: who meets whom each round; no repeat opponents. Generated when batch reaches 18.';
CREATE INDEX IF NOT EXISTS idx_batch_round_assignments_batch_round ON batch_round_assignments(batch_id, round_number);
CREATE INDEX IF NOT EXISTS idx_batch_round_assignments_participant ON batch_round_assignments(batch_id, round_number, participant_id_1);
CREATE INDEX IF NOT EXISTS idx_batch_round_assignments_p2 ON batch_round_assignments(batch_id, round_number, participant_id_2);

-- Generate round schedule for 18 participants (circle method)
CREATE OR REPLACE FUNCTION generate_batch_round_schedule(p_batch_id UUID)
RETURNS VOID AS $$
DECLARE
    v_count INTEGER;
    v_participant_ids UUID[] := '{}';
    v_i INTEGER;
    v_j INTEGER;
    v_p1 UUID;
    v_p2 UUID;
BEGIN
    SELECT count(*)::INTEGER INTO v_count
    FROM batch_participants WHERE batch_id = p_batch_id;

    IF v_count <> 18 THEN
        RETURN;
    END IF;

    IF EXISTS (SELECT 1 FROM batch_round_assignments WHERE batch_id = p_batch_id LIMIT 1) THEN
        RETURN;
    END IF;

    SELECT array_agg(participant_id ORDER BY joined_at, id)
    INTO v_participant_ids
    FROM batch_participants
    WHERE batch_id = p_batch_id;

    IF array_length(v_participant_ids, 1) <> 18 THEN
        RETURN;
    END IF;

    -- Round 1: (17,0),(1,16),(2,15),(3,14),(4,13),(5,12),(6,11),(7,10),(8,9)
    INSERT INTO batch_round_assignments (batch_id, round_number, participant_id_1, participant_id_2)
    VALUES
        (p_batch_id, 1, LEAST(v_participant_ids[18], v_participant_ids[1]), GREATEST(v_participant_ids[18], v_participant_ids[1])),
        (p_batch_id, 1, LEAST(v_participant_ids[2], v_participant_ids[17]), GREATEST(v_participant_ids[2], v_participant_ids[17])),
        (p_batch_id, 1, LEAST(v_participant_ids[3], v_participant_ids[16]), GREATEST(v_participant_ids[3], v_participant_ids[16])),
        (p_batch_id, 1, LEAST(v_participant_ids[4], v_participant_ids[15]), GREATEST(v_participant_ids[4], v_participant_ids[15])),
        (p_batch_id, 1, LEAST(v_participant_ids[5], v_participant_ids[14]), GREATEST(v_participant_ids[5], v_participant_ids[14])),
        (p_batch_id, 1, LEAST(v_participant_ids[6], v_participant_ids[13]), GREATEST(v_participant_ids[6], v_participant_ids[13])),
        (p_batch_id, 1, LEAST(v_participant_ids[7], v_participant_ids[12]), GREATEST(v_participant_ids[7], v_participant_ids[12])),
        (p_batch_id, 1, LEAST(v_participant_ids[8], v_participant_ids[11]), GREATEST(v_participant_ids[8], v_participant_ids[11])),
        (p_batch_id, 1, LEAST(v_participant_ids[9], v_participant_ids[10]), GREATEST(v_participant_ids[9], v_participant_ids[10]));

    -- Round 2: (17,1),(2,0),(3,16),(4,15),(5,14),(6,13),(7,12),(8,11),(9,10)
    INSERT INTO batch_round_assignments (batch_id, round_number, participant_id_1, participant_id_2)
    VALUES
        (p_batch_id, 2, LEAST(v_participant_ids[18], v_participant_ids[2]), GREATEST(v_participant_ids[18], v_participant_ids[2])),
        (p_batch_id, 2, LEAST(v_participant_ids[3], v_participant_ids[1]), GREATEST(v_participant_ids[3], v_participant_ids[1])),
        (p_batch_id, 2, LEAST(v_participant_ids[4], v_participant_ids[17]), GREATEST(v_participant_ids[4], v_participant_ids[17])),
        (p_batch_id, 2, LEAST(v_participant_ids[5], v_participant_ids[16]), GREATEST(v_participant_ids[5], v_participant_ids[16])),
        (p_batch_id, 2, LEAST(v_participant_ids[6], v_participant_ids[15]), GREATEST(v_participant_ids[6], v_participant_ids[15])),
        (p_batch_id, 2, LEAST(v_participant_ids[7], v_participant_ids[14]), GREATEST(v_participant_ids[7], v_participant_ids[14])),
        (p_batch_id, 2, LEAST(v_participant_ids[8], v_participant_ids[13]), GREATEST(v_participant_ids[8], v_participant_ids[13])),
        (p_batch_id, 2, LEAST(v_participant_ids[9], v_participant_ids[12]), GREATEST(v_participant_ids[9], v_participant_ids[12])),
        (p_batch_id, 2, LEAST(v_participant_ids[10], v_participant_ids[11]), GREATEST(v_participant_ids[10], v_participant_ids[11]));

    -- Round 3: (17,2),(3,1),(4,0),(5,16),(6,15),(7,14),(8,13),(9,12),(10,11)
    INSERT INTO batch_round_assignments (batch_id, round_number, participant_id_1, participant_id_2)
    VALUES
        (p_batch_id, 3, LEAST(v_participant_ids[18], v_participant_ids[3]), GREATEST(v_participant_ids[18], v_participant_ids[3])),
        (p_batch_id, 3, LEAST(v_participant_ids[4], v_participant_ids[2]), GREATEST(v_participant_ids[4], v_participant_ids[2])),
        (p_batch_id, 3, LEAST(v_participant_ids[5], v_participant_ids[1]), GREATEST(v_participant_ids[5], v_participant_ids[1])),
        (p_batch_id, 3, LEAST(v_participant_ids[6], v_participant_ids[17]), GREATEST(v_participant_ids[6], v_participant_ids[17])),
        (p_batch_id, 3, LEAST(v_participant_ids[7], v_participant_ids[16]), GREATEST(v_participant_ids[7], v_participant_ids[16])),
        (p_batch_id, 3, LEAST(v_participant_ids[8], v_participant_ids[15]), GREATEST(v_participant_ids[8], v_participant_ids[15])),
        (p_batch_id, 3, LEAST(v_participant_ids[9], v_participant_ids[14]), GREATEST(v_participant_ids[9], v_participant_ids[14])),
        (p_batch_id, 3, LEAST(v_participant_ids[10], v_participant_ids[13]), GREATEST(v_participant_ids[10], v_participant_ids[13])),
        (p_batch_id, 3, LEAST(v_participant_ids[11], v_participant_ids[12]), GREATEST(v_participant_ids[11], v_participant_ids[12]));

END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION generate_batch_round_schedule IS 'Pre-seed round schedule for 18 participants (circle method); idempotent.';

-- Pre-seeded flow: look up partner, create session when both in queue
CREATE OR REPLACE FUNCTION get_or_create_round_session(
    p_batch_id UUID,
    p_participant_id UUID,
    p_round_number INTEGER
)
RETURNS TABLE(session_id UUID, session_code TEXT, role TEXT, dyad_id UUID) AS $$
DECLARE
    v_partner_id UUID;
    v_condition TEXT;
    v_session_id UUID;
    v_session_code TEXT;
    v_dyad_id UUID;
    v_my_role TEXT;
BEGIN
    IF p_round_number < 1 OR p_round_number > 3 THEN
        RETURN;
    END IF;

    SELECT CASE
        WHEN bra.participant_id_1 = p_participant_id THEN bra.participant_id_2
        ELSE bra.participant_id_1
    END INTO v_partner_id
    FROM batch_round_assignments bra
    WHERE bra.batch_id = p_batch_id AND bra.round_number = p_round_number
      AND (bra.participant_id_1 = p_participant_id OR bra.participant_id_2 = p_participant_id);

    IF v_partner_id IS NULL THEN
        RETURN;
    END IF;

    INSERT INTO round_queue (participant_id, round_number)
    VALUES (p_participant_id, p_round_number)
    ON CONFLICT (participant_id, round_number) DO NOTHING;

    -- Session already exists for this pair + round?
    SELECT s.id, s.session_code, s.dyad_id INTO v_session_id, v_session_code, v_dyad_id
    FROM sessions s
    JOIN session_participants sp1 ON sp1.session_id = s.id AND sp1.participant_id = p_participant_id
    JOIN session_participants sp2 ON sp2.session_id = s.id AND sp2.participant_id = v_partner_id
    WHERE s.round_number = p_round_number
    LIMIT 1;

    IF v_session_id IS NOT NULL THEN
        SELECT sp.role INTO v_my_role FROM session_participants sp WHERE sp.session_id = v_session_id AND sp.participant_id = p_participant_id;
        session_id := v_session_id;
        session_code := v_session_code;
        role := v_my_role;
        dyad_id := v_dyad_id;
        RETURN NEXT;
        RETURN;
    END IF;

    -- Partner in queue?
    IF NOT EXISTS (SELECT 1 FROM round_queue WHERE participant_id = v_partner_id AND round_number = p_round_number) THEN
        RETURN;
    END IF;

    PERFORM 1 FROM round_queue
    WHERE (participant_id = p_participant_id OR participant_id = v_partner_id) AND round_number = p_round_number
    FOR UPDATE;

    -- Re-check (other transaction may have just created it)
    SELECT s.id INTO v_session_id
    FROM sessions s
    JOIN session_participants sp1 ON sp1.session_id = s.id AND sp1.participant_id = p_participant_id
    JOIN session_participants sp2 ON sp2.session_id = s.id AND sp2.participant_id = v_partner_id
    WHERE s.round_number = p_round_number LIMIT 1;
    IF v_session_id IS NOT NULL THEN
        SELECT s.session_code, s.dyad_id INTO v_session_code, v_dyad_id FROM sessions s WHERE s.id = v_session_id;
        SELECT sp.role INTO v_my_role FROM session_participants sp WHERE sp.session_id = v_session_id AND sp.participant_id = p_participant_id;
        session_id := v_session_id;
        session_code := v_session_code;
        role := v_my_role;
        dyad_id := v_dyad_id;
        RETURN NEXT;
        RETURN;
    END IF;

    -- Use first participant's condition for this round (deterministic)
    SELECT (bp.condition_order->>(p_round_number - 1))::TEXT INTO v_condition
    FROM batch_participants bp
    WHERE bp.batch_id = p_batch_id AND bp.participant_id = LEAST(p_participant_id, v_partner_id)
    LIMIT 1;

    IF v_condition IS NULL OR v_condition = '' THEN
        v_condition := 'v1.a';
    END IF;

    v_session_id := create_one_pool_session(
        LEAST(p_participant_id, v_partner_id)::UUID,
        GREATEST(p_participant_id, v_partner_id)::UUID,
        p_round_number,
        v_condition
    );

    DELETE FROM round_queue
    WHERE (participant_id = p_participant_id OR participant_id = v_partner_id) AND round_number = p_round_number;

    SELECT s.session_code, s.dyad_id INTO v_session_code, v_dyad_id FROM sessions s WHERE s.id = v_session_id;
    SELECT sp.role INTO v_my_role FROM session_participants sp WHERE sp.session_id = v_session_id AND sp.participant_id = p_participant_id;

    session_id := v_session_id;
    session_code := v_session_code;
    role := v_my_role;
    dyad_id := v_dyad_id;
    RETURN NEXT;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION get_or_create_round_session IS 'Pre-seeded flow: look up partner, create session when both in queue; returns session+role or null.';


-- ============================================================
-- Migration 019: Join Batch Generate Schedule
-- When 18th participant joins, auto-generate the pre-seeded schedule
-- ============================================================

CREATE OR REPLACE FUNCTION join_batch_atomic(p_batch_id UUID, p_participant_id UUID)
RETURNS batch_participants AS $$
DECLARE
    v_batch experiment_batches;
    v_count INTEGER;
    v_perm_index INTEGER;
    v_condition_order JSONB;
    v_row batch_participants;
BEGIN
    SELECT * INTO v_batch
    FROM experiment_batches
    WHERE id = p_batch_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Batch not found';
    END IF;
    IF v_batch.status <> 'open' THEN
        RAISE EXCEPTION 'Batch is not open for joining';
    END IF;

    SELECT * INTO v_row
    FROM batch_participants
    WHERE batch_id = p_batch_id AND participant_id = p_participant_id;
    IF FOUND THEN
        RETURN v_row;
    END IF;

    v_count := (SELECT count(*)::INTEGER FROM batch_participants WHERE batch_id = p_batch_id);
    IF v_count >= v_batch.max_participants THEN
        RAISE EXCEPTION 'Batch is full';
    END IF;

    v_perm_index := (v_count / 2) % 6;
    v_condition_order := CASE v_perm_index
        WHEN 0 THEN '["v1.a","v1.b","v1.c"]'::JSONB
        WHEN 1 THEN '["v1.a","v1.c","v1.b"]'::JSONB
        WHEN 2 THEN '["v1.b","v1.a","v1.c"]'::JSONB
        WHEN 3 THEN '["v1.b","v1.c","v1.a"]'::JSONB
        WHEN 4 THEN '["v1.c","v1.a","v1.b"]'::JSONB
        ELSE '["v1.c","v1.b","v1.a"]'::JSONB
    END;

    INSERT INTO batch_participants (batch_id, participant_id, condition_order)
    VALUES (p_batch_id, p_participant_id, v_condition_order)
    RETURNING * INTO v_row;

    -- Pre-seed round schedule when batch reaches max (e.g. 18)
    IF (v_count + 1) = v_batch.max_participants THEN
        PERFORM generate_batch_round_schedule(p_batch_id);
    END IF;

    RETURN v_row;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION join_batch_atomic IS 'Atomic batch join; when 18th joins, generates pre-seeded round schedule.';


-- ============================================================
-- Migration 020: Add to Round Queue RPC
-- ============================================================

CREATE OR REPLACE FUNCTION add_to_round_queue(p_participant_id UUID, p_round_number INTEGER)
RETURNS VOID AS $$
BEGIN
    IF p_round_number < 1 OR p_round_number > 3 THEN
        RETURN;
    END IF;
    INSERT INTO round_queue (participant_id, round_number)
    VALUES (p_participant_id, p_round_number)
    ON CONFLICT (participant_id, round_number) DO NOTHING;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION add_to_round_queue IS 'Idempotent: add participant to round queue (e.g. when lobby page loads so first poll can match).';


-- ============================================================
-- Migration 021: Batch Has Schedule
-- ============================================================

CREATE OR REPLACE FUNCTION batch_has_schedule(p_batch_id UUID)
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (SELECT 1 FROM batch_round_assignments WHERE batch_id = p_batch_id LIMIT 1);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER STABLE;

COMMENT ON FUNCTION batch_has_schedule IS 'True if this batch has pre-seeded round assignments; lobby should not use condition-based fallback when true.';


-- ============================================================
-- Migration 022: Test Batch Six Participants
-- Support pre-seeded schedule for 6 participants (test batch)
-- ============================================================

CREATE OR REPLACE FUNCTION generate_batch_round_schedule(p_batch_id UUID)
RETURNS VOID AS $$
DECLARE
    v_count INTEGER;
    v_participant_ids UUID[] := '{}';
BEGIN
    SELECT count(*)::INTEGER INTO v_count
    FROM batch_participants WHERE batch_id = p_batch_id;

    IF v_count NOT IN (6, 12, 18) THEN
        RETURN;
    END IF;

    IF EXISTS (SELECT 1 FROM batch_round_assignments WHERE batch_id = p_batch_id LIMIT 1) THEN
        RETURN;
    END IF;

    SELECT array_agg(participant_id ORDER BY joined_at, id)
    INTO v_participant_ids
    FROM batch_participants
    WHERE batch_id = p_batch_id;

    IF array_length(v_participant_ids, 1) IS NULL OR array_length(v_participant_ids, 1) <> v_count THEN
        RETURN;
    END IF;

    -- ========== 6 participants (test batch): 3 pairs per round ==========
    IF v_count = 6 THEN
        -- Round 1: (1,6),(2,5),(3,4)
        INSERT INTO batch_round_assignments (batch_id, round_number, participant_id_1, participant_id_2)
        VALUES
            (p_batch_id, 1, LEAST(v_participant_ids[1], v_participant_ids[6]), GREATEST(v_participant_ids[1], v_participant_ids[6])),
            (p_batch_id, 1, LEAST(v_participant_ids[2], v_participant_ids[5]), GREATEST(v_participant_ids[2], v_participant_ids[5])),
            (p_batch_id, 1, LEAST(v_participant_ids[3], v_participant_ids[4]), GREATEST(v_participant_ids[3], v_participant_ids[4]));
        -- Round 2: (2,6),(1,3),(4,5)
        INSERT INTO batch_round_assignments (batch_id, round_number, participant_id_1, participant_id_2)
        VALUES
            (p_batch_id, 2, LEAST(v_participant_ids[2], v_participant_ids[6]), GREATEST(v_participant_ids[2], v_participant_ids[6])),
            (p_batch_id, 2, LEAST(v_participant_ids[1], v_participant_ids[3]), GREATEST(v_participant_ids[1], v_participant_ids[3])),
            (p_batch_id, 2, LEAST(v_participant_ids[4], v_participant_ids[5]), GREATEST(v_participant_ids[4], v_participant_ids[5]));
        -- Round 3: (3,6),(2,4),(1,5)
        INSERT INTO batch_round_assignments (batch_id, round_number, participant_id_1, participant_id_2)
        VALUES
            (p_batch_id, 3, LEAST(v_participant_ids[3], v_participant_ids[6]), GREATEST(v_participant_ids[3], v_participant_ids[6])),
            (p_batch_id, 3, LEAST(v_participant_ids[2], v_participant_ids[4]), GREATEST(v_participant_ids[2], v_participant_ids[4])),
            (p_batch_id, 3, LEAST(v_participant_ids[1], v_participant_ids[5]), GREATEST(v_participant_ids[1], v_participant_ids[5]));
        RETURN;
    END IF;

    -- ========== 12 participants (medium batch): 6 pairs per round ==========
    -- Circle method: fix participant 12, rotate 1-11
    IF v_count = 12 THEN
        -- Round 1: (12,1),(2,11),(3,10),(4,9),(5,8),(6,7)
        INSERT INTO batch_round_assignments (batch_id, round_number, participant_id_1, participant_id_2)
        VALUES
            (p_batch_id, 1, LEAST(v_participant_ids[12], v_participant_ids[1]), GREATEST(v_participant_ids[12], v_participant_ids[1])),
            (p_batch_id, 1, LEAST(v_participant_ids[2], v_participant_ids[11]), GREATEST(v_participant_ids[2], v_participant_ids[11])),
            (p_batch_id, 1, LEAST(v_participant_ids[3], v_participant_ids[10]), GREATEST(v_participant_ids[3], v_participant_ids[10])),
            (p_batch_id, 1, LEAST(v_participant_ids[4], v_participant_ids[9]), GREATEST(v_participant_ids[4], v_participant_ids[9])),
            (p_batch_id, 1, LEAST(v_participant_ids[5], v_participant_ids[8]), GREATEST(v_participant_ids[5], v_participant_ids[8])),
            (p_batch_id, 1, LEAST(v_participant_ids[6], v_participant_ids[7]), GREATEST(v_participant_ids[6], v_participant_ids[7]));
        -- Round 2: (12,2),(3,1),(4,11),(5,10),(6,9),(7,8)
        INSERT INTO batch_round_assignments (batch_id, round_number, participant_id_1, participant_id_2)
        VALUES
            (p_batch_id, 2, LEAST(v_participant_ids[12], v_participant_ids[2]), GREATEST(v_participant_ids[12], v_participant_ids[2])),
            (p_batch_id, 2, LEAST(v_participant_ids[3], v_participant_ids[1]), GREATEST(v_participant_ids[3], v_participant_ids[1])),
            (p_batch_id, 2, LEAST(v_participant_ids[4], v_participant_ids[11]), GREATEST(v_participant_ids[4], v_participant_ids[11])),
            (p_batch_id, 2, LEAST(v_participant_ids[5], v_participant_ids[10]), GREATEST(v_participant_ids[5], v_participant_ids[10])),
            (p_batch_id, 2, LEAST(v_participant_ids[6], v_participant_ids[9]), GREATEST(v_participant_ids[6], v_participant_ids[9])),
            (p_batch_id, 2, LEAST(v_participant_ids[7], v_participant_ids[8]), GREATEST(v_participant_ids[7], v_participant_ids[8]));
        -- Round 3: (12,3),(4,2),(5,1),(6,11),(7,10),(8,9)
        INSERT INTO batch_round_assignments (batch_id, round_number, participant_id_1, participant_id_2)
        VALUES
            (p_batch_id, 3, LEAST(v_participant_ids[12], v_participant_ids[3]), GREATEST(v_participant_ids[12], v_participant_ids[3])),
            (p_batch_id, 3, LEAST(v_participant_ids[4], v_participant_ids[2]), GREATEST(v_participant_ids[4], v_participant_ids[2])),
            (p_batch_id, 3, LEAST(v_participant_ids[5], v_participant_ids[1]), GREATEST(v_participant_ids[5], v_participant_ids[1])),
            (p_batch_id, 3, LEAST(v_participant_ids[6], v_participant_ids[11]), GREATEST(v_participant_ids[6], v_participant_ids[11])),
            (p_batch_id, 3, LEAST(v_participant_ids[7], v_participant_ids[10]), GREATEST(v_participant_ids[7], v_participant_ids[10])),
            (p_batch_id, 3, LEAST(v_participant_ids[8], v_participant_ids[9]), GREATEST(v_participant_ids[8], v_participant_ids[9]));
        RETURN;
    END IF;

    -- ========== 18 participants (full batch): 9 pairs per round ==========
    -- Round 1
    INSERT INTO batch_round_assignments (batch_id, round_number, participant_id_1, participant_id_2)
    VALUES
        (p_batch_id, 1, LEAST(v_participant_ids[18], v_participant_ids[1]), GREATEST(v_participant_ids[18], v_participant_ids[1])),
        (p_batch_id, 1, LEAST(v_participant_ids[2], v_participant_ids[17]), GREATEST(v_participant_ids[2], v_participant_ids[17])),
        (p_batch_id, 1, LEAST(v_participant_ids[3], v_participant_ids[16]), GREATEST(v_participant_ids[3], v_participant_ids[16])),
        (p_batch_id, 1, LEAST(v_participant_ids[4], v_participant_ids[15]), GREATEST(v_participant_ids[4], v_participant_ids[15])),
        (p_batch_id, 1, LEAST(v_participant_ids[5], v_participant_ids[14]), GREATEST(v_participant_ids[5], v_participant_ids[14])),
        (p_batch_id, 1, LEAST(v_participant_ids[6], v_participant_ids[13]), GREATEST(v_participant_ids[6], v_participant_ids[13])),
        (p_batch_id, 1, LEAST(v_participant_ids[7], v_participant_ids[12]), GREATEST(v_participant_ids[7], v_participant_ids[12])),
        (p_batch_id, 1, LEAST(v_participant_ids[8], v_participant_ids[11]), GREATEST(v_participant_ids[8], v_participant_ids[11])),
        (p_batch_id, 1, LEAST(v_participant_ids[9], v_participant_ids[10]), GREATEST(v_participant_ids[9], v_participant_ids[10]));

    -- Round 2
    INSERT INTO batch_round_assignments (batch_id, round_number, participant_id_1, participant_id_2)
    VALUES
        (p_batch_id, 2, LEAST(v_participant_ids[18], v_participant_ids[2]), GREATEST(v_participant_ids[18], v_participant_ids[2])),
        (p_batch_id, 2, LEAST(v_participant_ids[3], v_participant_ids[1]), GREATEST(v_participant_ids[3], v_participant_ids[1])),
        (p_batch_id, 2, LEAST(v_participant_ids[4], v_participant_ids[17]), GREATEST(v_participant_ids[4], v_participant_ids[17])),
        (p_batch_id, 2, LEAST(v_participant_ids[5], v_participant_ids[16]), GREATEST(v_participant_ids[5], v_participant_ids[16])),
        (p_batch_id, 2, LEAST(v_participant_ids[6], v_participant_ids[15]), GREATEST(v_participant_ids[6], v_participant_ids[15])),
        (p_batch_id, 2, LEAST(v_participant_ids[7], v_participant_ids[14]), GREATEST(v_participant_ids[7], v_participant_ids[14])),
        (p_batch_id, 2, LEAST(v_participant_ids[8], v_participant_ids[13]), GREATEST(v_participant_ids[8], v_participant_ids[13])),
        (p_batch_id, 2, LEAST(v_participant_ids[9], v_participant_ids[12]), GREATEST(v_participant_ids[9], v_participant_ids[12])),
        (p_batch_id, 2, LEAST(v_participant_ids[10], v_participant_ids[11]), GREATEST(v_participant_ids[10], v_participant_ids[11]));

    -- Round 3
    INSERT INTO batch_round_assignments (batch_id, round_number, participant_id_1, participant_id_2)
    VALUES
        (p_batch_id, 3, LEAST(v_participant_ids[18], v_participant_ids[3]), GREATEST(v_participant_ids[18], v_participant_ids[3])),
        (p_batch_id, 3, LEAST(v_participant_ids[4], v_participant_ids[2]), GREATEST(v_participant_ids[4], v_participant_ids[2])),
        (p_batch_id, 3, LEAST(v_participant_ids[5], v_participant_ids[1]), GREATEST(v_participant_ids[5], v_participant_ids[1])),
        (p_batch_id, 3, LEAST(v_participant_ids[6], v_participant_ids[17]), GREATEST(v_participant_ids[6], v_participant_ids[17])),
        (p_batch_id, 3, LEAST(v_participant_ids[7], v_participant_ids[16]), GREATEST(v_participant_ids[7], v_participant_ids[16])),
        (p_batch_id, 3, LEAST(v_participant_ids[8], v_participant_ids[15]), GREATEST(v_participant_ids[8], v_participant_ids[15])),
        (p_batch_id, 3, LEAST(v_participant_ids[9], v_participant_ids[14]), GREATEST(v_participant_ids[9], v_participant_ids[14])),
        (p_batch_id, 3, LEAST(v_participant_ids[10], v_participant_ids[13]), GREATEST(v_participant_ids[10], v_participant_ids[13])),
        (p_batch_id, 3, LEAST(v_participant_ids[11], v_participant_ids[12]), GREATEST(v_participant_ids[11], v_participant_ids[12]));
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION generate_batch_round_schedule IS 'Pre-seed round schedule for 6, 12, or 18 participants (circle method); idempotent.';


-- ============================================================
-- Migration 023: Notify Triggers (self-hosted realtime)
-- These replace Supabase Realtime's postgres_changes subscriptions.
-- Each trigger fires pg_notify() with a JSON payload containing the
-- session_id and the full row, which the Node.js server picks up
-- via PG LISTEN and broadcasts to Socket.io rooms.
-- ============================================================

-- 1. messages INSERT
CREATE OR REPLACE FUNCTION notify_messages_insert() RETURNS trigger AS $$
BEGIN
  PERFORM pg_notify('messages_insert', json_build_object(
    'session_id', NEW.session_id,
    'row', row_to_json(NEW)
  )::text);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_messages_insert ON messages;
CREATE TRIGGER trg_messages_insert
  AFTER INSERT ON messages
  FOR EACH ROW EXECUTE FUNCTION notify_messages_insert();

-- 2. sessions UPDATE
CREATE OR REPLACE FUNCTION notify_sessions_update() RETURNS trigger AS $$
BEGIN
  PERFORM pg_notify('sessions_update', json_build_object(
    'session_id', NEW.id,
    'row', row_to_json(NEW)
  )::text);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_sessions_update ON sessions;
CREATE TRIGGER trg_sessions_update
  AFTER UPDATE ON sessions
  FOR EACH ROW EXECUTE FUNCTION notify_sessions_update();

-- 3. session_participants INSERT
CREATE OR REPLACE FUNCTION notify_session_participants_insert() RETURNS trigger AS $$
BEGIN
  PERFORM pg_notify('session_participants_insert', json_build_object(
    'session_id', NEW.session_id,
    'row', row_to_json(NEW)
  )::text);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_session_participants_insert ON session_participants;
CREATE TRIGGER trg_session_participants_insert
  AFTER INSERT ON session_participants
  FOR EACH ROW EXECUTE FUNCTION notify_session_participants_insert();

-- 4. session_participants UPDATE
CREATE OR REPLACE FUNCTION notify_session_participants_update() RETURNS trigger AS $$
BEGIN
  PERFORM pg_notify('session_participants_update', json_build_object(
    'session_id', NEW.session_id,
    'row', row_to_json(NEW)
  )::text);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_session_participants_update ON session_participants;
CREATE TRIGGER trg_session_participants_update
  AFTER UPDATE ON session_participants
  FOR EACH ROW EXECUTE FUNCTION notify_session_participants_update();


-- ============================================
-- END OF CONSOLIDATED SCHEMA
-- ============================================
